spring:
  application:
    name: community-news-backend

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

aws:
  region: us-east-1
  s3:
    bucket-name: community-news-images
  dynamodb:
    table-name: NewsPosts
  sqs:
    queue-url: https://sqs.us-east-1.amazonaws.com/000000000000/ImageResizeTaskQueue

