spring:
  application:
    name: community-news-board

cloud:
  aws:
    s3:
      bucket: community-news-poze-2026

aws:
  region: eu-central-1
  dynamodb:
    auto-create-tables: true
  sqs:
    queue-name: ImageResizeTaskQueue
    auto-create-queue: true

auth:
  password:
    algorithm: PBKDF2WithHmacSHA256
